const l = ["acnaway acne patch  infinity-size",
"acnaway acne patch day ultra-thin",
"acnaway stubborn acne cream",
"acne gel bee clear 10ml",
"acne patch let's glow hydrocolloid bear",
"acne patch let's glow hydrocolloid bulan",
"acne patch let's glow hydrocolloid butterfly",
"acne patch let's glow hydrocolloid love",
"acne patch let's glow hydrocolloid sakura",
"acne patch let's glow hydrocolloid star",
"acnes creamy wash 100gr",
"acnes creamy wash 50g",
"acnes facewash complete white 100gr",
"acnes facewash complete white 50gr",
"acnes facewash deep pore cleanser 100gr",
"acnes facewash deep pore cleanser 50gr",
"acnes facewash oil control 100gr",
"acnes facewash oil control 50gr",
"acnes facewash yogurt touch 100gr",
"acnes facewash yogurt touch 50gr",
"acnes mentholatum pore strip",
"acnes milk cleanser oil control 110ml",
"acnes oil control film",
"acnes oil control mask",
"acnes point clear mini roll-on 9ml",
"acnes sealing jell 18gr",
"acnes sealing jell 9gr",
"acnes spot care 12gr",
"acnes starter pack",
"acnes tea tree oil clay mask 50gr",
"acnes toner oil control 110ml",
"acnes uv tint natural beige SPF 35PA+++ 30gr",
"acnes uv tint natural green SPF 35PA+++ 30gr",
"acnes washing bar 80gr | bar soap",
"acnoc aceser anti acne gel 15gr",
"acnol lotion 10ml",
"adara bee clear extra formula",
"allphv blackhead mask step 1 17ml",
"ariul smooth & pure cleansing foam 50ml",
"autumn toner skin conditioner with centella asiatica",
"avoskin azeclair 10% + kombucha 3% + niacinamide 2.5% vaccine serum",
"avoskin marine collagen 10%+ginseng root ",
"avoskin miraculous refining toner 100ml",
"avoskin miraculous retinol ampoule 30ml",
"avoskin miraculous retinol toner 100ml",
"avoskin niacinamide 12%+centella asiatic ",
"avoskin salicylic acid 2% + zinc",
"avoskin spirulina + witch azel +glycoid acid niacinamide ",
"avoskin tea tree + witch azel + glycoid acid rosemary ",
"avoskin the great shield sun-essence spf 50 5ml",
"avoskin ysb alpha arbutin 3%",
"avoskin ysb lactic acid 10% 30ml",
"avoskin ysb panthenol 5%+mughwort+cica",
"avoskin ysb ultimate hyaluron hyacross3%+greentea",
"avoskin ysb vitamin c 3% + niacinamide 2%",
"axis-y cera-heart my type duo cream 60ml",
"axis-y daily toner",
"axis-y dark spot correcting glow serum 10ml",
"axis-y dark spot correcting glow serum 50ml",
"axis-y new skin resolution gel mask",
"axis-y the mini glow set",
"ayodya slim tea original ",
"ayodya slimming tea roselle",
"azarine active bright brightening creamy facial foam 50g",
"azarine advanced you barrier moist (ungu)",
"azarine anti aging serum 20ml",
"azarine aqua essence sun shield serum SPF 50 100ml",
"azarine blackhead remover mask 7ml",
"azarine blemish rescue acne gentle cleansing foam 60ml",
"azarine blemish rescue mild purifying toner 90ml",
"azarine blemish rescue oil free brightening daily moisturizer 40ml",
"azarine brightening c-glow serum 20ml",
"azarine c white brightening facial cleanser",
"azarine c white day cream spf 30 25gr",
"azarine c white eye luminate firming serum 15ml",
"azarine c white multi-acids glowing toner 90ml",
"azarine c white night moisturizer 25gr",
"azarine calm my acne sunscreen 40g",
"azarine calming skinpair serum 20ml",
"azarine cicamide barrier sunscreen SPF 35",
"azarine daily beginner exfoliatiing toner ",
"azarine daily defender multivitamin serum",
"azarine face mist",
"azarine fresh radiant brightening scrub 50g",
"azarine hydramax-C sunscreen 40ml",
"azarine hydrasoothe sunscreen mist 60ml",
"azarine hydrasoothe sunscreen SPF 45 30ml",
"azarine hydrasoothe sunscreen SPF 45 50ml",
"azarine intense luminous barrier moist (biru)",
"azarine marvel acne spot serum 20ml",
"azarine marvel aha-bha-pha peeling serum 20ml",
"azarine marvel hydramax water bank serum 20ml",
"azarine marvel miracle oil serum 20ml",
"azarine marvel niacinamide 5% serum 20ml",
"azarine marvel pore tightening serum 20ml",
"azarine marvel radiant luminous serum ",
"azarine marvel retinol smooth glowing serum ",
"azarine moisture rich hydrating toner 90ml",
"azarine polypeptide fresh vitality toner ",
"azarine pure radiance barrier moist (hijau)",
"azarine purifying deep cleansing clay mask 60gr",
"azarine revitalizing anti aging serum 20ml",
"azarine tone up mineral sunscreen serum 27ml",
"azarine vitamin lab let it glow hydraveil primer serum 20ml",
"azarine vitamin lab matte my day hydraveil primer serum 20ml",
"azrina acne purifying clay mask",
"azrina pure charcoal mud mask 50ml",
"bandana",
"beaudelab collagen powder drink | newlab+ collagen drink",
"beauty blender young beauty",
"bio beauty lab acne treatment facial oil serum 10ml",
"bio beauty lab acne treatment facial oil serum 5ml",
"bio beauty lab luxurious facial oil serum 10ml",
"bio beauty lab luxurious facial oil serum 5ml",
"bio oil minyak perawatan kulit 25ml",
"bioaqua 24K essence cream",
"bioaqua 24K gold body wash 400ml",
"bioaqua sheetmask aloe vera",
"bioaqua sheetmask apple",
"bioaqua sheetmask avocado",
"bioaqua sheetmask blackcurrant",
"bioaqua sheetmask blueberry",
"bioaqua sheetmask carrot",
"bioaqua sheetmask centella ",
"bioaqua sheetmask chamomile",
"bioaqua sheetmask cherry",
"bioaqua sheetmask coconut ",
"bioaqua sheetmask cucumber",
"bioaqua sheetmask dragon fruit",
"bioaqua sheetmask grape copper ",
"bioaqua sheetmask grape fruit",
"bioaqua sheetmask honey",
"bioaqua sheetmask kiwi",
"bioaqua sheetmask lemon vit c",
"bioaqua sheetmask orange ",
"bioaqua sheetmask papaya",
"bioaqua sheetmask peach",
"bioaqua sheetmask pomegranate",
"bioaqua sheetmask sea buckthom ",
"bioaqua sheetmask tomato",
"blinkz soap 60gr",
"bloomka happy barrier melted moisturizer",
"breylee blackhead mask step 1 17ml",
"breylee step 2",
"breylee tea tree nose strips",
"byout by nisa brightening spot cream",
"byout by nisa cream morning glowing",
"byout by nisa cream wajah glowing 2 whitening super",
"byout by nisa eye dark circle serum",
"byout by nisa facial wash acne clear ",
"byout by nisa facial wash brightening arbutin",
"byout by nisa new acne glowing",
"byout by nisa toner norml skin | brightening toner",
"camille little pop face mist 100ml",
"carasun solar smart uv protector 30ml",
"carasun solar smart uv protector sunscreen 8ml",
"cetaphil gentle skin cleanser 1000ml",
"cetaphil gentle skin cleanser 125ml",
"cetaphil gentle skin cleanser 250ml",
"cetaphil gentle skin cleanser 500ml",
"cetaphil gentle skin cleanser 59ml",
"cetaphil moisturizing lotion 59ml (hijau)",
"chava face mist organic 100gr",
"cleora beauty 3 minutes exfoliating gel 50ml",
"cosrx acne pimple masker patch",
"cosrx advanced snail 96 mucin power essence 100ml",
"cosrx low ph good morning gel cleanser 150ml",
"cosrx low ph good morning gel cleanser 20ml",
"cosrx low ph good morning gel cleanser 50ml",
"cosrx AHA/BHA Clarifiying treatment toner",
"daisy organic chocolate 20gr",
"daisy organic greentea 20gr",
"daisy organic milk 20gr",
"daisy organic strawberry 20gr",
"dazzle me lip tin oran-gee",
"dazzle me lip tin smiley",
"dazzle me lip tin swipe up",
"dazzle me lip tin touch down",
"dear me beauty 10% vitamin C + orange extract face serum 12ml",
"derma angel acne gel patch day 12",
"derma angel acne gel patch night 12",
"derma angel acne gel patch night 6",
"derma angel acne patch day 6pcs",
"derma angel acne path mix 18pcs",
"diy compressed mask 100pcs",
"dorskin matcha glow dream mask 30gr",
"dr brandon brightening & firm serum 20ml",
"dr brandon brightening face serum 20ml",
"dr brandon hydrating face serum",
"dr brandon intensive bright serum alpha arbutin centella asiatica 20ml",
"dr brandon peeling solution 20ml",
"eiem beauty water bank moisture gel 30gr",
"eiem serum niacinamide",
"eileen grace deep cleansing black jelly mask 300ml",
"eileen grace moisturize rose jelly mask 300ml",
"emina bright stuff face wash 100ml",
"emina bright stuff face wash 50ml",
"emina lip mask",
"emina sun battle Sunscreen SPF 30 60ml",
"emina sun battle Sunscreen SPF 30 Fun Size 23ml",
"envygreen acne shot solution 10ml",
"envygreen bye bye flake lips lip scrub 7gr",
"envygreen clean pore facial foam 30ml",
"envygreen clean pore toner 100ml",
"envygreen clean pore toner 30ml",
"envygreen clear daily protection 5gr",
"envygreen dead skin cell remover ",
"envygreen eye and neck hyalugen serum 3ml",
"envygreen gentle and fresh face toner 100ml",
"envygreen gentle and fresh face toner 30ml",
"envygreen gentle and fresh facial foam 100ml",
"envygreen gentle and fresh facial foam 30ml",
"envygreen glow up exfoliating toner 100ml",
"envygreen glow up exfoliating toner 30ml",
"envygreen hyalugen skin barrier serum 15ml",
"envygreen hyalugen skin barrier serum 3ml",
"envygreen intensify brightening serum 3ml",
"envygreen moisture boost cream 25gr",
"envygreen mugcera intensify brightening serum 10ml",
"envygreen night extra whitening 20gr",
"envygreen night extra whitening 5gr",
"envygreen pore refining minimizer serum 10ml",
"envygreen pore refining minimizer serum 5ml",
"envygreen skin bestie soothing toner 60ml",
"envygreen soft moist and nourish cream 25gr",
"envygreen soft moist and nourish cream 5gr",
"envygreen ultimate sun protection 20gr",
"envygreen ultimate sun protection 5gr",
"er123 cleanser",
"facetology facial wash",
"facetology triple care sunscreen spf 40PA+++",
"fameux whitening body cream",
"focallure eyebrow cream 01 auburn",
"focallure eyebrow cream 02",
"focallure eyebrow cream 03",
"focallure eyebrow cream 04",
"focallure eyebrow cream 05 ebony",
"focallure patch acne day",
"focallure patch acne night",
"garnier micellar cleansing water in oil 125ml (biphas)",
"garnier micellar cleansing water pink 125ml",
"garnier micellar cleansing water pink 400ml",
"garnier micellar cleansing water pink 50ml",
"garnier micellar cleansing water rose water 125ml",
"garnier micellar cleansing water salicylic bha 125ml (biru)",
"garnier micellar cleansing water vitamin C 125ml",
"garnier micellar oil-infused cleansing water 50ml",
"geamoore body wash bacca 540 100ml",
"geamoore body wash bo coffee 100ml",
"geamoore body wash jmlone 100ml",
"geamoore collaberry minuan serbuk 55gr",
"geamoore parfum addict 15ml blush sunny",
"geamoore parfum addict 15ml cotton candy",
"geamoore parfum addict 15ml flamingo fame",
"geamoore parfum addict 15ml greentelova",
"geamoore parfum addict 15ml peach cookies",
"geamoore parfum addict 15ml vanillatte",
"geamoore parfum addict 5ml blush sunny",
"geamoore parfum addict 5ml cotton candy",
"geamoore parfum addict 5ml flamingo fame",
"geamoore parfum addict 5ml greentelova",
"geamoore parfum addict 5ml peach cookies",
"geamoore parfum addict 5ml vanillatte",
"geamoore parfum baby backaratz 30ml",
"geamoore parfum baby backaratz 6ml",
"geamoore parfum baby sweet powder 30ml",
"geamoore parfum baby sweet powder 6ml",
"geamoore parfum backaratz 30ml",
"geamoore parfum backaratz 6ml",
"geamoore parfum blackophie 30ml",
"geamoore parfum blackophie 6ml",
"geamoore parfum peachy oh baby 30ml",
"geamoore parfum peachy oh baby 6ml",
"geamoore parfum peony joo malone 30ml",
"geamoore parfum peony joo malone 6ml",
"geamoore parfum the scandalous 30ml",
"geamoore parfum the scandalous 6ml",
"geamoore parfum vanilla 30ml",
"geamoore parfum vanilla 6ml",
"girlpal centella asiatica peeling gel",
"glad2glow blueberry ceramide low ph gel cleanser ",
"glad2glow blueberry moist",
"glad2glow centella 2% ceramide soothing toner 40ml",
"glad2glow centella moisturizer 30gr",
"glad2glow centella moisturizer 55gr",
"glad2glow jeju tangerine vita c power bright glow serum 17ml ",
"glad2glow milk amino acids gentle cleanser 80g",
"glad2glow niacinamide pomegrante 5% niacinamide brightening moist 30ml",
"glad2glow pomegranate 10% niacinamide power bright serum ",
"glad2glow real mugwort salicyc acid acne control clay mask ",
"glad2glow sunscreen SPF 50",
"glad2glow volcano 3D acid pore clay mask 30gr",
"glad2glow volcano 3D acid pore clay stick ",
"glad2glow yuja symwhite 377 dark spot moisture",
"gloria minty sunscreen spray 2 in 1 60ml",
"gluta collagen soap chocowhite",
"golden vierra soap",
"grace and glow black opium brightening sun body serum 100ml ",
"grace and glow body serum black opium 300ml",
"grace and glow body serum english pear 300ml",
"grace and glow body serum miss moisture 300ml",
"grace and glow body serum peony blush",
"grace and glow body serum rouge 300ml",
"grace and glow body wash black opium/brightening solution",
"grace and glow body wash english pear",
"grace and glow body wash miss moisture",
"grace and glow body wash peony blush soft",
"grace and glow body wash rouge 540",
"grace and glow daisy hair vitamin mist kuning 100ml",
"grace and glow deodorant black opium",
"grace and glow deodorant english pear",
"grace and glow deodorant moiselle 50ml",
"grace and glow deodorant rouge 540 50ml",
"grace and glow nourish shampoo secret bombshell",
"grownlash 10ml",
"gua sha biru / guasha biru",
"gua sha hijau / guasha hijau",
"gua sha pink / guasha pink",
"gua sha putih / guasha putih",
"gua sha ungu / guasha ungu purple",
"hada labo goku jyun alpha ultimate anti-aging lotion ",
"hada labo goku jyun alpha ultimate anti-aging milk",
"hada labo goku jyun stater pack alpha ultimate anti aging ",
"hada labo goku jyun stater pack ultimate moisturizing ",
"hada labo goku jyun ultimate moisturizing face wash 100gr",
"hada labo goku jyun ultimate moisturizing face wash 50gr",
"hada labo goku jyun ultimate moisturizing light lotion 100ml",
"hada labo goku jyun ultimate moisturizing lotion 100ml",
"hada labo goku jyun ultimate moisturizing milk 100ml",
"hada labo mild peeling aha + bha face wash 100gr",
"hada labo mild peeling aha + bha face wash 50gr",
"hada labo shiro jyun starter pack",
"hada labo shiro jyun ultimate whitening face wash 100gr",
"hada labo shiro jyun ultimate whitening face wash 50gr",
"hada labo shiro jyun ultimate whitening lotion 100ml",
"hada labo shiro jyun ultimate whitening milk 100ml",
"hadalabo goku jyun cleansing oil lotion ",
"hanasui body spa body exfoliating gel aloe vera 300ml ",
"hanasui body spa body exfoliating gel blueberry 300ml",
"hanasui body spa body exfoliating gel cherry 300ml",
"hanasui body spa body exfoliating gel coffee 300ml",
"hanasui body spa body exfoliating gel lemon 300ml",
"hanasui body spa body exfoliating gel orange 300ml",
"hanasui body spa body exfoliating gel rainbow 300ml",
"hanasui body spa body exfoliating gel rice 300ml",
"hanasui body spa body exfoliating gel strawberry 300ml",
"hanasui collagen water spf 50 PA++++ 30ml",
"hanasui collagen water sunscreen spf 30",
"hanasui eyedorable mascara",
"hanasui eyetractive liner pen",
"hanasui fix & glow setting spray 60ml",
"hanasui flawless-glow 10 gentle cleanser 60gr",
"hanasui flawless-glow 10 starter kit",
"hanasui lip sleeping serum",
"hanasui mattedorable lip cream 01 forest berry",
"hanasui mattedorable lip cream 02 brown sugar",
"hanasui mattedorable lip cream 03 salted caramel",
"hanasui mattedorable lip cream 04 pink lava",
"hanasui mattedorable lip cream 05 creamy peach",
"hanasui mattedorable lip cream 06 hazelnut latte",
"hanasui men bright active serum ",
"hanasui milky lotion 240ml",
"hanasui naturgo lightening peel off mask 60gr",
"hanasui perfect cheek blush & go 01 pink",
"hanasui perfect cheek blush & go 02 peach",
"hanasui power acne serum",
"hanasui power bakuchiol serum",
"hanasui power barrier serum",
"hanasui power bright serum",
"Hanasui power BrightExpert serum",
"hanasui power minipore serum ",
"hanasui power peeling serum",
"hanasui power post acne serum",
"hanasui serum anti acne (pink)",
"hanasui serum cushion 01 light 15gr",
"hanasui serum cushion 02 natural 15gr",
"hanasui serum cushion 03 15gr",
"hanasui serum vit c + collagen (biru)",
"hanasui serum vitamin C 20ml (kuning)",
"hanasui serum whitening gold 20ml (gold)",
"hanasui tintdorable lip stain 02 peachy",
"hanasui tintdorable lip stain 05 coral",
"hanasui tintdorable lip stain bloody 06",
"hanasui tintdorable lip stain cherry 01",
"hanasui tintdorable lip stain ruby 03",
"hanasui tintdorable lip stain sweet 04",
"hatomugi skin conditioner 500ml",
"hb jepang bodycream cherry blossom",
"himalaya purifying neem mask 100ml ",
"himalaya purifying neem mask 50ml ",
"ibcccndc eyebrow powder black",
"ibcccndc eyebrow powder brown",
"ibcccndc eyebrow powder dark brown ",
"images beautecret black",
"images eye patch collagen crytal",
"images eye patch collagen moisturizing eye mask 7.5gr",
"images eye patch green mung bean crystal penetration eye mask 7.5gr",
"images eye patch seaweed elastic white tender eye mask (hijau)",
"images eye patsc golden osmanthus crystal moisture eye mask 7.5gr",
"implora 24K gold serum 20ml",
"implora acne serum 20ml",
"implora bakuchiol serum",
"implora birdnest skin nouris serum ",
"implora cheek & liptint 01 vampire blood",
"implora cheek & liptint 02 cherry bomb",
"implora cheek & liptint 03 candy apple",
"implora cheek & liptint 04 red wine",
"implora cheek & liptint 05 cranberry",
"implora cheek & liptint 06 pumpkin",
"implora eyebrow pencil black",
"implora eyebrow pencil brown",
"implora eyebrow pencil dark brown",
"implora eyebrow pencil grey  brown",
"implora eyebrow pencil silver",
"implora hydrating serum 20ml",
"implora jelly tint 01 mariposa",
"implora jelly tint 02 savvy red",
"implora jelly tint 03 true vintage",
"implora jelly tint 04 rosy posy",
"implora jelly tint 05 dream peach",
"implora jelly tint 06 flamingo",
"implora jelly tint 07 sangria",
"implora jelly tint 08 burnt orange",
"implora jelly tint 09 rosewood",
"implora lip crayon satin 01-curious",
"implora lip crayon satin first kiss",
"implora lip crayon satin jealousy",
"implora lip crayon satin misery",
"implora lip crayon satin play date",
"implora lip crayon satin promises",
"implora lip moist essence",
"implora lip moist serum",
"implora lip velvet attractive",
"implora lip velvet extrovert",
"implora lip velvet fearless",
"implora lip velvet honest",
"implora lip velvet naive",
"implora lip velvet serenity",
"implora luminous brightening serum 20ml",
"implora midnight serum 20ml",
"implora peeling serum 20ml",
"implora perfect shield sunscreen SPF 40 50ml",
"implora salmon DNA serum ",
"implora urban lip cream matte 02 terra cotta",
"implora urban lip cream matte 03 dark berry",
"implora urban lip cream matte 05 allure",
"implora urban lip cream matte 07 truffle mauve",
"implora urban lip cream matte 08 pink latte",
"implora urban lip cream matte 09 butterscotch",
"implora urban lip cream matte 10 gingerbread",
"implora urban lip cream matte 12 brown sugar",
"implora urban lip cream matte 18 ruby",
"implora urban lipcream 16 dusty peach ",
"implora urban lipcream matte 01 dusky nude ",
"implora urban lipcream matte 06 lumiere ",
"implora urban lipcream matte 11 red bean ",
"implora urban lipcream matte 13 hazelnude",
"implora urban lipcream matte 14 baby rose ",
"implora urban lipcream matte 15 salmon pink ",
"implora urban lipcream matte 17 redwoood ",
"implora urban lipcream matte 19 carolina ",
"implora urban lipcream matte 20 red gala ",
"jade roler",
"jarte sunscreen spray 30ml",
"jiera lip serum 10ml",
"k brothers soap 60gr sabun beras thailand",
"kahf face wash brightening(biru)",
"kahf face wash gentle exfoliating face scrub 100ml(coklat)",
"kahf face wash oil and acne care 100ml (hijau)",
"kahf face wash triple action oil and comedo defense 100ml(hitam)",
"kapas selection 175pcs",
"kapas selection 60gram",
"kleveru sea buckthorn cleansing gel 100ml",
"kojie san soap 135gr",
"kojie san soap 45gr",
"kojie san soap 65gr",
"kojie san soap travel pack",
"kuas make-up brush",
"kutus kutus tamba waras minyak balur 100ml",
"la personal acne patch butterfly",
"la personal acne patch circle",
"lacoco dark spot essence 12ml",
"lacoco intensive treatment eye serum 15ml",
"lae sa luay keratin smooth shampoo 200ml",
"lae sa luay spa smooth keratin 250ml",
"laneige lip sleeping mask",
"laneige water sleeping mask_ex 15ml",
"larissa obat totol jerawat",
"lashboss rapunzel serum for lash and brow 5.5ml | lash boss",
"lea gloria peel off mask with petals lavender 15gr",
"lea gloria peel off mask with petals rose 15gr",
"lippie serum",
"lomira lip serum colour",
"lucido vitamin hair spray kuning",
"lucido vitamin hair spray orange ",
"lucido vitamin hair spray pink",
"Lunadream mugwort rose peeling solution 15gr",
"Lunadream mugwort rose peeling solution 30gr",
"Lunadream sunscreen",
"madame gia shower glow 01 joy",
"madame gie bamboo charcoal & black sugar mini peel of mask ",
"madame gie charmseeker 2in1 ombre 01 cheeky",
"madame gie charmseeker 2in1 ombre 02 sassy",
"madame gie charmseeker 2in1 ombre 03 baddie",
"madame gie concealer 3gr beige",
"madame gie concealer 3gr ivory",
"madame gie concealer 3gr tan",
"madame gie let's glow tinted sunscreen 10ml (biru) 01 light",
"madame gie let's glow tinted sunscreen 10ml (biru) 02 medium",
"madame gie let's glow tinted sunscreen 10ml (biru) 03 deep",
"madame gie lippil lip serum 01",
"madame gie pimple spot cream acne solution",
"madame gie protect me sunscreen spf 30 pa+++",
"madame gie protect me sunscreen spf 50 pa+++",
"madame gie shower glow 02",
"madame gie shower glow 03 calm",
"madame gie skin barrier moisturizer 50ml",
"madame lip pills berry jam",
"madame lip pills bold wine",
"madame lip pills butterscoth",
"madame lip pills cotton candy",
"madame lip pills mulberry cane",
"madame lip pills sweet cherry",
"madame lip pills witchs syrup",
"madamegie avocado & oatmeal mini peel of mask ",
"madamegie honeydew & chamomile mini peel of mask ",
"madamegie lemon &honey mini peel of mask ",
"makarizo hair energy blue coast hair & body fragrance 100ml",
"makarizo hair energy cherry blossoms hair & body fragrance 100ml",
"makarizo hair energy fresh bouquet hair fragrance 100ml",
"makarizo hair energy morning dew hair & body fragrance 100ml",
"makarizo hair energy ocean breeze hair fragance 100ml",
"makarizo hair energy shampoo aloe vera 170ml",
"makarizo hair energy shampoo kiwi extract 170ml",
"makarizo hair energy shampoo olive extract 170ml",
"makarizo hair energy shampoo royal jelly extract 170ml",
"makarizo hair energy white musk hair & body fragrance 100ml",
"mako fresh glowy skin day & night moisture",
"mako fresh glowy sleeping mask 20gr",
"mako toner essence mist 60ml",
"mangkok set masker",
"marina natural lotion apple  grapefruits and sunscreen 190ml pink",
"marina natural lotion apple  grapefruits and sunscreen 95ml pink",
"marina natural lotion avocado and olive oil 190ml hijau",
"marina natural lotion avocado and olive oil 95ml hijau",
"marina natural lotion honey and macadamia 190ml orange",
"marina natural lotion honey and macadamia 95ml orange",
"marina natural lotion sweet almond and chia almond 190ml kuning",
"marina natural lotion sweet almond and chia almond 95ml kuning",
"marina natural lotion vit.c  vit.e  pro-vit.d3 and oat 190ml ungu",
"marina natural lotion vit.c  vit.e pro-vit.d3 and oat 95ml ungu",
"marshwillow candy cane 110",
"marshwillow candy cane 112",
"marshwillow candy crush biru",
"marshwillow candy crush hijau",
"marshwillow candy crush kuning",
"marshwillow candy crush orange",
"marshwillow candy crush pink ",
"marshwillow candy crush ungu",
"marshwillow eyebrow pencil black",
"marshwillow eyebrow pencil brown",
"marshwillow eyebrow pencil dark brown",
"marshwillow mascara extra volume (pink)",
"marshwillow mascara eyeliner (pink tua)",
"marshwillow mascara maxi curl (pink tua)",
"marshwillow mascara overcurl (biru)",
"masker mata hitam",
"masker mata pink",
"masker spirulina",
"mathiswomen patch acne bear and duck",
"mathiswomen patch acne butterfly ",
"mathiswomen patch acne clear",
"mathiswomen patch acne clouds",
"mathiswomen patch acne love",
"mathiswomen patch acne sakura ",
"mathiswomen patch acne star",
"maybelline hyper curl waterproof mascara",
"mayra bright and glow serum 20ml",
"milk recipe 4in1 hair removal cream 70gr",
"mimi white aha body lotion 200ml",
"mimi white aha body serum 100ml",
"mimi white aha body serum 30",
"mimi white aha lotion 100ml",
"moriganic uv watery sun cream 40gr",
"mykonos vanilla clouds 100ml",
"mykonos vanilla clouds 50ml",
"mykonos vanilla clouds 50ml",
"nature republic aloevera",
"neogen bio-peel gauze peeling lemon 30pcs",
"noera bright and glow serum 20ml",
"noera collagen drink peach 15pcs",
"noera collagen drink peach 7pcs",
"noera collagen drink strawberry 15pcs",
"noera collagen drink strawbery 7pcs",
"noera glowme skin 30 kapsul",
"noera skin lightening cream",
"noera slim boost",
"noera slimming tea 120gr 60kantong",
"noera slimming tea 60gr 30kantong",
"noera vita lip serum",
"noera watermelon lip scrub 5gr",
"noera watermelon moisturizing lip balm 5gr",
"npure centella asiatica face toner 150ml",
"npure centella asiatica face toner 30ml",
"npure cica acne spot 20gr",
"npure cica beat the sun powder 5gr",
"npure cica chocomint clay mask",
"npure cica clear pad sachet",
"npure licorice light up brightening pad gentle exfoliating ",
"npure noni probiotics gel cleanser 100ml",
"npure noni probiotics gel cleanser 50ml",
"nu face nu glow acne prone care facial wash ",
"nu face nu glow acne prone care toner ",
"nu face nu glow brighten & supple skin facial wash ",
"nu face nu glow brighten & supple skin Toner ",
"nu face nu glow hydra lock &youthful skin facial wash",
"nu face nu glow hydra lock &youthful skin toner",
"nutrishe intensive bright & glow serum 20ml",
"nutrishe intensive bright & glow serum 30ml",
"oh my glow mask saffron detox greentea 25gr",
"oh my glow mask saffron freshy minty 25gr",
"oh my glow mask saffron glow honey 25gr",
"oh my glow mask saffron sakura 25gr",
"OMG oh my glam coverlast two way cake | bedak padat 21W light",
"OMG oh my glam coverlast two way cake | bedak padat 32N natural",
"OMG oh my glam coverlast two way cake | bedak padat 41W sand",
"OMG oh my glam lip cream matte kiss 01 creamy",
"OMG oh my glam lip cream matte kiss 02 juicy",
"OMG oh my glam lip cream matte kiss 03 flame",
"OMG oh my glam lip cream matte kiss 04 sunset",
"OMG oh my glam lip cream matte kiss 05 punch",
"OMG oh my glam lip cream matte kiss 06 sparkle",
"OMG oh my glam lip cream matte kiss 07 delight",
"OMG oh my glam lip cream matte kiss 08 skyfall",
"OMG oh my glam lip cream matte kiss 09 charm",
"OMG oh my glam lip cream matte kiss 10 shell",
"OMG oh my glam lip cream matte kiss 11 bumble",
"OMG oh my glam lip cream matte kiss 12 scarlett",
"OMG oh my glam lip cream matte kiss 13 latte",
"OMG oh my glam lip cream matte kiss 14 cappucino",
"OMG oh my glam lip cream matte kiss 15 espresso",
"OMG oh my glam lip cream matte kiss 16 elegant",
"OMG oh my glam lip cream matte kiss 17 queen",
"OMG oh my glam lip cream matte kiss 18 luxe",
"OMG oh my glam liquid foundation 32N natural",
"OMG oh my glam liquid pondation 13c ivory",
"OMG oh my glam liquid pondation 21w light",
"OMG oh my glam liquid pondation 21w sand",
"OMG oh my glam liquid pondation 31w beige",
"OMG oh my glam liquid pondation 52N caramel",
"pencukur alis/pisau alis",
"phesha beauty cream colek ",
"phesha beauty cream tube 50ml",
"pinkflash auto eyebrow 01  natural brown ",
"pinkflash auto eyebrow 02 chocolate brown",
"pinkflash auto eyebrow 03 gray brown",
"pinkflash auto eyebrow 04 natural gray",
"pinkflash baby skin blender",
"pinkflash care plus lip oil",
"pinkflash eyebrown pencil PF-E02 02 Natural Brown",
"pinkflash eyebrown pencil PF-E02 03 Chocolate Brown",
"pinkflash eyebrown pencil PF-E02 04 dark gray Brown",
"pinkflash eyebrown pencil PF-E02 Latte Brown",
"pinkflash eyeshadow palette 01",
"pinkflash eyeshadow palette 02",
"pinkflash eyeshadow palette 03",
"pinkflash eyeshadow palette 04",
"pinkflash lasting matte foundation #2 sand beige",
"pinkflash lasting matte foundation #3 warm beige ",
"pinkflash lasting matte foundation #4 medium peach",
"pinkflash lasting matte foundation #6 tan ",
"pinkflash lasting matte foundation 05 ",
"pinkflash lasting matte lipcream BB01",
"pinkflash lasting matte lipcream N01",
"pinkflash lasting matte lipcream N02",
"pinkflash lasting matte lipcream N03",
"pinkflash lasting matte lipcream N04",
"pinkflash lasting matte lipcream N05",
"pinkflash lasting matte lipcream N06",
"pinkflash lasting matte lipcream O01",
"pinkflash lasting matte lipcream O02",
"pinkflash lasting matte lipcream O03",
"pinkflash lasting matte lipcream O04",
"pinkflash lasting matte lipcream OR05",
"pinkflash lasting matte lipcream P01",
"pinkflash lasting matte lipcream P02",
"pinkflash lasting matte lipcream P03",
"pinkflash lasting matte lipcream P04",
"pinkflash lasting matte lipcream PK05",
"pinkflash lasting matte lipcream R01",
"pinkflash lasting matte lipcream R02",
"pinkflash lasting matte lipcream R03",
"pinkflash lasting matte lipcream R04",
"pinkflash loose powder #000",
"pinkflash loose powder #111",
"pinkflash loose powder #222",
"pinkflash matte pressed powder #000",
"pinkflash matte pressed powder #111",
"pinkflash matte pressed powder #222",
"pinkflash oil proof curl mascara black",
"pinkflash oil proof curl mascara pink",
"pinkflash soft smooth cotton pads 40pcs",
"pinkflash waterproof easy eyeliner PF-E01 black",
"pinkflash waterproof easy eyeliner PF-E01 brown",
"pinkkflash soft pigment blush 001 ",
"pinkkflash soft pigment blush 002",
"pinkkflash soft pigment blush 003 ",
"pinkkflash soft pigment blush N01",
"pinkkflash soft pigment blush N02",
"pinkkflash soft pigment blush N03",
"pinkkflash soft pigment blush P01",
"pinkkflash soft pigment blush P02",
"pinkkflash soft pigment blush P03",
"pixy beauty skin primer",
"pratista calming spray 100ml",
"pratista hyalu hydrating toner",
"precious alpha arbutin collagen body serum 500ml",
"precious alpha arbutin collagen foaming cleanser",
"precious alpha arbutin lotion 500ml",
"precious alpha arbutin salt scrub",
"precious alpha arbutin whitening plus (kapsul pemutih)",
"precious skin aha body booster serum 30ml",
"precious skin aha body soap 80gr",
"precious skin alpha arbutin organic underarm night cream 50gr",
"precious skin alpha arbutin soap 80gr",
"precious skin kojic collagen soap 60gr",
"pure paw paw passion fruit 25gr",
"pyunkang yul essence toner 100ml",
"pyunkang yul essence toner 200ml",
"pyunkang yul essence toner 30ml",
"pyunkang yul mist toner 100ml",
"pyunkang yul mist toner 200ml",
"pyunkang yul essense toner 10ml",
"QL Mascara waterproof&curling",
"rd123 gold day cream",
"rd123 gold night cream",
"rd123 sabun",
"rd123 toner",
"rd123 vitamin c serum collagen ",
"sabun papaya RDL",
"sacrlett body lotion charming",
"saffron face mist 100ml (tanpa label)",
"saffron mist 100ml (dengan label)",
"salsa hair serum growth (merah)",
"salsa hair serum keratin repair hair serum (kuning)",
"salsa hair serum rose (pink)",
"salsa vinylash eyelash",
"saturday looks minty clay mask 125gr",
"saturday looks minty gentle scrub 125gr",
"scarlett 7x ceramide moisturizer",
"scarlett acne cream night 20gr",
"scarlett acne day cream",
"scarlett acne essence toner 100ml",
"scarlett acne facial wash 100ml",
"scarlett acne night cream",
"scarlett acne serum 15ml",
"scarlett acne to glow mini series",
"scarlett body lotion fantasia 300ml",
"scarlett body lotion freshy 300ml",
"scarlett body scrub coffee 250ml",
"scarlett body scrub pomegrante 250ml",
"scarlett body scrub romansa 250ml",
"scarlett body serum cerathione hyalu charming 250ml",
"scarlett body serum cerathione hyalu happy 250ml",
"scarlett body serum cerathione hyalu jolly 250ml",
"scarlett body serum cerathione hyalu loving 250ml",
"scarlett brightening day cream",
"scarlett brightening facial wash 100ml",
"scarlett brightening shower charming 300ml",
"scarlett brightening shower coffee 300ml",
"scarlett brightening shower cucumber 300ml",
"scarlett brightening shower freshy 300ml",
"scarlett brightening shower jolly 300ml",
"scarlett brightening shower mango 300ml",
"scarlett brightening shower pomegrante 300ml",
"scarlett brightly essence toner 100ml",
"scarlett brightly ever after cream 20gr",
"scarlett brightly ever after serum 15ml",
"scarlett brightly to glow mini series",
"scarlett c-power serum 15ml",
"scarlett fragance brightening body lotion charming 180ml",
"scarlett fragance brightening body lotion jolly 180ml",
"scarlett fragance brightening body lotion romansa 180ml",
"scarlett fragrance body cream 7x ceramide charming 300ml",
"scarlett fragrance body cream 7x ceramide happy 300ml",
"scarlett fragrance body cream 7x ceramide jolly 300ml",
"scarlett fragrance body cream 7x ceramide loving 300ml",
"scarlett glowtening serum 15ml",
"scarlett herbalism mugwort mask 100gr",
"scarlett seriously soothing & hydrating gel mask 100gr",
"scarlett yordania shampoo (kemasan lama)",
"scarlett yordanian sea salt conditioner 250ml",
"scarlett yordanian sea salt conditioner 250ml (kemasan lama)",
"seomgum glowing soap ",
"sexy boobs",
"sheeby beauty collagen",
"shinzui skin lightening body cleanser hana 180ml",
"shinzui skin lightening body cleanser kensho 180ml",
"shinzui skin lightening body cleanser kirei 200ml",
"shinzui skin lightening body cleanser matsu 180ml",
"shinzui skin lightening body cleanser myori 200ml",
"shinzui skin lightening body cleanser sakura 180ml",
"shinzui skin lightening body cleanser sakura 200ml",
"shinzui skin lightening body scrub hana 110gr",
"shinzui skin lightening body scrub hana 200gr",
"shinzui skin lightening body scrub kensho 110gr",
"shinzui skin lightening body scrub kensho 200gr",
"shinzui skin lightening body scrub kirei 200gr",
"shinzui skin lightening body scrub matsu 120gr",
"shinzui skin lightening body scrub matsu 200gr",
"shinzui skin lightening body scrub myori 110gr",
"shinzui skin lightening body scrub myori 200gr",
"shinzui skin lightening body scrub sakura 110gr",
"shinzui skin lightening body scrub sakura 200gr",
"shinzui skin lighteninh body scrub kirei 110gr",
"shinzui skin ligtening body cleanser hana 200ml",
"shinzui skin ligtening body cleanser kensho 200ml",
"shower puff / spon mandi",
"skin aqua | skinaqua tone up essence hijau spf 50",
"skin aqua sunscreen whitening milk spf 50",
"skin aqua tone up uv essence spf 50+ 40gr",
"skin aqua UV Mild Milk SPF 25 PA++",
"skin aqua UV Moisture Gel SPF 30 PA++",
"skin aqua UV Moisture Milk SPF 50 PA ++",
"skin aqua UV whitening Milk SPF 20 PA++ ",
"skin game acne warrior | skingame",
"skintific 2% salicylic acid anti acne serum 20ml",
"skintific 4D hyaluronic acid barrier essence toner 20ml",
"skintific 5% aha bha pha exfoliating toner 80ml",
"skintific 5x ceramide barrier repair moisture gel 30gr",
"skintific 5x ceramide barrier repair moisture gel 6gr",
"skintific 5x ceramide barrier repair serum 20ml",
"skintific 5x ceramide low ph cleanser 15ml",
"skintific 5x ceramide low ph cleanser 80ml",
"skintific 5x ceramide soothing toner 20ml",
"skintific 5x ceramide soothing toner 80ml",
"skintific crystal massager lifting eye cream 20gr",
"skintific msh niacinamide moisturizer 6gr (pink)",
"skintific mugwort anti pores & acne clay mask 55g",
"skintific mugwort anti pores & acne clay stick 40gr",
"skintific retinol cream pelembab moisturizer",
"skintific salycylic acid acne spot treatment",
"slimming kapus 30kapsul",
"some by mi / somebymi yuja niacin serum 50ml",
"some by mi bye bye blackhead bubble cleanser",
"some by mi propolis b5 glow barrier calming serum 50ml",
"some by mi propolis b5 glow barrier calming toner 50ml",
"some by mi red teatree cicassoside 60gr",
"some by mi snail truecica miracle repair serum 50ml",
"some by mi super matcha pore clean clay mask ",
"some by mi super matcha pore clean cleansing gel 100ml ",
"some by mi super matcha pore tightening serum 50ml",
"some by mi super matcha pore tightening toner 150ml",
"some by mi yuja niacin 30 days brightening starter kit",
"some by mi yuja niacin brightening sleeping mask 15gr",
"somethinc aha bha pha peeling solution 20ml",
"somethinc bakuchiol skinpair oil serum ",
"somethinc calm down pha 3% everyday toner 100ml",
"somethinc calm down pha 3% everyday toner 40ml",
"somethinc ceramic skin saviour 25ml",
"somethinc ceramic skin saviour 50ml",
"somethinc fabric lasting tint ambitious",
"somethinc game changer",
"somethinc hangover mascara",
"somethinc low ph gentle jelly cleanser 100ml",
"somethinc low ph gentle jelly cleanser 15ml",
"somethinc niacinamide barrier 5% 20ml",
"somethinc reset gentle micellar cleansing water 160ml",
"somethinc reset gentle micellar cleansing water 40ml",
"somethinc scandal waterproof eyeliner dark choco",
"somethinc serum lemonade vit c",
"somethinc serum revive 3%",
"somethinc sunscreen sglowing up tick spf 50",
"somethinc supple power 120ml",
"somethinc supple power 60ml",
"spatula biru",
"spatula kecil",
"spatula orange",
"spatula pink",
"spatula ungu",
"spons bedak | Spon Bedak",
"ssp sabun susu pemutih",
"studio tropik herbitus skin tonic 100ml",
"sukin signature foaming facial cleanser 125ml",
"sukin signature natural deodorant 125ml",
"sunscreen hiqween",
"tender compaction eye mask 7.5gr",
"the aubree ceramide soft cream 30g",
"the ordinary niacinamide 10% + zinc 1% 30ml",
"the orifginote txa 377 dark spot serum",
"the originote acne B5 serum",
"the originote asthaciol serum",
"the originote ceraluronic essence toner",
"the originote ceratides barrier serum ",
"the originote gluta bright b3 serum",
"the originote hyalu-c serum",
"the originote lip oil serum",
"the originote moisturizer 50ml",
"the originote peeling solution serum",
"the originote retinol b3 serum",
"true to skin matcha oat gentle cleanser",
"true to skin matcha oat gentle cleanser 15ml",
"tumitku",
"vaseline gluta hya dewy radiance 200ml",
"vaseline gluta hya flawless bright 200ml",
"vavl beauty water",
"vavl blemish water strong",
"vavl sunscreen",
"vightne vavl blemish serum 15ml",
"vightne vavl pure white brightening face wash 100ml",
"vightne vavl pure white glowing serum 15ml",
"vightne vavl pure white whitening night cream 12gr",
"vio acne patch",
"viva air mawar",
"viva anti aging serum",
"viva face tonic bengkoang 100ml",
"viva face tonic cucumber",
"viva face tonic greentea",
"viva face tonic lemon",
"viva face tonic original 100ml",
"viva face tonic spirulina",
"viva glowing white serum",
"viva milk cleanser bengkoang 100ml",
"viva milk cleanser cucumber",
"viva milk cleanser greentea",
"viva milk cleanser lemon",
"viva milk cleanser original 100ml",
"viva milk cleanser spirulina",
"viva peeling serum",
"wardah  lightening micellar gentle wash 100ml",
"wardah acnederm acne spot gel 15ml",
"wardah acnederm day moisturizer 40ml",
"wardah acnederm night cream moisturizer",
"wardah acnederm pure foaming cleanser 60ml",
"wardah acnederm toner",
"wardah fruity sheer lip balm grape 4 gr",
"wardah fruity sheer lip balm strawberry 4gr",
"wardah lightening cleansing milk 100ml",
"wardah lightening day cream 20ml",
"wardah lightening day cream 30ml",
"wardah lightening face mist 60ml",
"wardah lightening face toner 125ml",
"wardah lightening gentle exfo 50ml",
"wardah lightening matte powder 01 neutral fair",
"wardah lightening matte powder 02 neutral beige",
"wardah lightening matte powder 03 warm ivory",
"wardah lightening matte powder 04 light ivory",
"wardah lightening micellar gentel wash 50ml",
"wardah lightening night cream 20ml",
"wardah lightening night cream 30ml",
"wardah lightening oil-infused micellar water 50ml",
"wardah lightening serum ampoule 30ml",
"wardah lightening serum ampoule 8ml",
"wardah moisture lip nutrision greentea",
"wardah moisture lip nutrision honey ",
"wardah moisture lip nutrision strawberry",
"wardah seaweed cleansing micellar water 100ml",
"wardah sunscreen spf 50 active",
"wardah uv shield spf 35",
"wardah uv shield spf 50",
"whitelab acne care facial wash ",
"whitelab acne cream 10gr",
"whitelab acne serum 20ml",
"whitelab acne soap 80gr",
"whitelab acne toner",
"whitelab bamboo charcoal brightening gel mask",
"whitelab brightening day cream 20gr",
"whitelab brightening facial wash 100gr",
"whitelab brightening night cream 20gr",
"whitelab brightening toner 100ml",
"whitelab C-Dose+ brightening serum 20ml",
"whitelab cera-mug barrier moisturizing gel 20gr",
"whitelab exfoliating toner",
"whitelab eye cream 10gr",
"whitelab hydrating face essence 60ml",
"whitelab hydrating serum ",
"whitelab intensive care serum 15ml",
"whitelab mugwort pore clarifying mask",
"whitelab N10 Dose brightening serum",
"whitelab N5 Dose brightening serum",
"whitelab ph balanced facial cleanser",
"whitelab retinol treatment serum",
"whitelab soothing toner 60ml",
"whitelab uv shield tank sunscreen gel spf 50 pa++++ 30gr",
"xi xiu divine eyebrow matic pencil  black ",
"xi xiu divine eyebrow matic pencil  brown ",
"xi xiu eyebrow pensil alis black ",
"xi xiu eyebrow pensil alis brown",
"xi xiu eyeliner (pink)",
"xi xiu ultimate eyeliner pen (putih)",
"yoni toner badan 100ml",
"you acne plus B5 soothing sheet mask ",
"you acneplus triple action spot care",
"you hy amino ac ttack facial wash anti acne",
"you hy amino bye byeteria facial wash",
"you hy amino contr oil facial wash",
"you hy amino wow tery facial wash",
"you hyl amino facial wash ",
"zozu alpukat masker mata",
"zozu gold masker mata"];

const f = [
  [1, "Tanpa Brand"],
[2, "Acnaway"],
[3, "Acnes"],
[4, "Acnoc"],
[5, "Adara"],
[6, "Allphv"],
[7, "Ariul"],
[8, "Autumn"],
[9, "Avoskin"],
[10, "Axisyy"],
[11, "Ayodya"],
[12, "Azarine"],
[13, "Azrina"],
[14, "Beaudelab"],
[15, "Bio Beauty Lab"],
[16, "Bioaqua"],
[17, "Blinkz"],
[18, "Bloomka"],
[19, "Breylee"],
[20, "Byout By Nisa"],
[21, "Camille"],
[22, "Carasun"],
[23, "Cetaphil"],
[24, "Chava"],
[25, "Cleora"],
[26, "Cosrx"],
[27, "Daisy"],
[28, "Dazzle Me"],
[29, "Dear Me Beauty"],
[30, "Derma Angel"],
[31, "Diy"],
[32, "Dorskin"],
[33, "Dr Brandon"],
[34, "Eiem Beauty"],
[35, "Eileen Grace"],
[36, "Emina"],
[37, "Envygreen"],
[38, "Er123"],
[39, "Facetology"],
[40, "Fameux"],
[41, "Focallure"],
[42, "Garnier"],
[43, "Geamoore"],
[44, "Girlpal"],
[45, "Glad2Glow"],
[46, "Gloria Mintyl"],
[47, "Gluta"],
[48, "Golden Vierra"],
[49, "Grace And Glow"],
[50, "Grownlash"],
[51, "Hada Labo"],
[52, "Hanasui"],
[53, "Hatomugi"],
[54, "Hb Jepang"],
[55, "Himalaya"],
[56, "Ibcccndc"],
[57, "Implora"],
[58, "Jarte"],
[59, "Jiera"],
[60, "K Brothers"],
[61, "Kahf"],
[62, "Kleveru"],
[63, "Kojie San"],
[64, "La Personal"],
[65, "Lacoco Dark"],
[66, "Lae Sa Luay"],
[67, "Laneige"],
[68, "Larissa"],
[69, "Lashboss"],
[70, "Lea Gloria"],
[71, "Lippie"],
[72, "Lomira"],
[73, "Lucido"],
[74, "Lunadream"],
[75, "Madame Gie"],
[76, "Makarizo"],
[77, "Mako"],
[78, "Marina"],
[79, "Marshwillow"],
[80, "Mathiswomen"],
[81, "Maybelline"],
[82, "Mayra"],
[83, "Milk Recipe"],
[84, "Mimi"],
[85, "Moriganic"],
[86, "Mykonos"],
[87, "Nature Republic"],
[88, "Neogen"],
[89, "Noera"],
[90, "Npure"],
[91, "Nu Face"],
[92, "Nutrishe"],
[93, "Oh My Glow"],
[94, "Omg Oh My Glam"],
[95, "Phesha"],
[96, "Pinkflash"],
[97, "Pixy Beauty"],
[98, "Pratista"],
[99, "Precious"],
[100, "Pure Paw Paw"],
[101, "Pyunkang Yul"],
[102, "Rd123"],
[103, "Sacrlett"],
[104, "Salsa"],
[105, "Saturday Looks"],
[106, "Seomgum"],
[107, "Sheeby Beauty"],
[108, "Shinzui"],
[109, "Skin Aqua"],
[110, "Skintific"],
[111, "Some By Mi"],
[112, "Somethinc"],
[113, "Ssp"],
[114, "Studio Tropik"],
[115, "Sukin Signature"],
[116, "The Aubree"],
[117, "The Ordinary"],
[118, "The Orifginote"],
[119, "True To Skin"],
[120, "Tumitku"],
[121, "Vaseline"],
[122, "Vavl"],
[123, "Vightne"],
[124, "Vio"],
[125, "Viva"],
[126, "Wardah"],
[127, "Whitelab"],
[128, "Xi Xiu"],
[129, "Yoni"],
[130, "You"],
[131, "Zozu"]
]; 


function title(str) {
  return str.replace(/(^|\s)\S/g, function(t) { return t.toUpperCase() });
}

var fs = require('fs')
var logger = fs.createWriteStream('log.csv', {
  flags: 'a' // 'a' means appending (old data will be preserved)
})

logger.write(`brand_id,name,category_id,updated_at,is_active,store_id\r\n`);

// f.map((v) => {
//   const ll = v[1].toLowerCase().replace(/\s+/gi, '');
//   const len = ll.trim().length;

//   l.map((n, i) => {
//     const nm = n.toLowerCase().replace(/\s+/gi, '');
//     const subs = nm.trim().substring(0, len);
    
//     if(subs === ll){
//       logger.write(`${v[0]},${title(n)},1,2024-01-16 04:50:55,1\r\n`);
//     } else {
//       logger.write(`1,${title(n)},1,2024-01-16 04:50:55,1\r\n`);
//     }
//   })
// })

l.map((n) => {
  const nm = n.toLowerCase().replace(/\s+/gi, '');
  let cid = 1;

  f.map((s) => {
    const ll = s[1].toLowerCase().replace(/\s+/gi, '');
    const len = ll.trim().length;

    const subs = nm.trim().substring(0, len);
    
    if(subs === ll){
      cid = s[0];
      return;
    } 

  })

  logger.write(`${cid},${title(n)},1,2024-01-16 04:50:55,1,1\r\n`);

})